export { default as logoCodePrimary } from "./{code}-trouble-logo-primary.svg";
export { default as logoCodePrimaryFull } from "./{code} trouble.svg";
export { default as discord } from "./discord.svg";
export { default as email } from "./email.svg";
export { default as github } from "./github.svg";
export { default as instagram } from "./instagram.svg";
export { default as whatsApp } from "./whatsapp.svg";
export { default as linkedIn } from "./linkedIn.svg";
export { default as dribbleSocial } from "./dribbbleSocial.svg";
export { default as linkedinSocial } from "./linkedinSocial.svg";
export { default as githubSocial } from "./githubSocial.svg";
export { default as behanceSocial } from "./behanceSocial.svg";
